-- Author: Matthew Cash
-- Project: New Wheels – SQL Business Analysis
-- Environment: Great Learning SQL Lab
-- Description: Queries designed to answer key business questions for quarterly reporting


-- New Wheels Project - Quarterly Business Reporting

-- Objective: Use the data to answer the questions posed and create a quarterly business report 

-- Question 1: Find the total number of customers who have placed orders. What is the distribution of the customers across states?

-- Part 1
SELECT 
    COUNT(DISTINCT customer_id) AS Customers_Who_Placed_Orders
FROM order_t;

-- Part 2
SELECT 
    c.state,
    COUNT(DISTINCT customer_id) AS num_customers 
FROM customer_t c 
    JOIN order_t o USING(customer_id)
WHERE quantity IS NOT NULL
GROUP BY 
    c.state
ORDER BY 
    num_customers DESC;


-- Question 2: Which are the top 5 vehicle makers preferred by the customers?

SELECT  
    p.vehicle_maker,
    COUNT(DISTINCT customer_id) AS num_customers
FROM product_t p 
    JOIN order_t o USING(product_id)
    JOIN customer_t c USING(customer_id)
GROUP BY 
    p.vehicle_maker
ORDER BY
    num_customers DESC
LIMIT 5;



-- Question 3: Which is the most preferred vehicle maker in each state?

SELECT  
    state,
    vehicle_maker,
    customer_count
FROM (
    SELECT 
        c.state,
        p.vehicle_maker,
        COUNT(DISTINCT c.customer_id) AS customer_count,
        RANK() OVER(PARTITION BY c.state ORDER BY COUNT(DISTINCT c.customer_id) DESC) AS rnk
    FROM
    product_t p 
    JOIN order_t o USING(product_id)
    JOIN customer_t c USING(customer_id)
    GROUP BY 
        c.state,
        p.vehicle_maker)
WHERE rnk = 1
ORDER BY state;

-- Question 4: Find the overall average rating given by the customers. What is the average rating in each quarter?

-- Part 1: Finding the Overall Average Rating given by customers
SELECT  
    ROUND(AVG(feedback_num_value), 2) as Overall_Avg_Rating
FROM (
    SELECT
        o.quarter_number AS QuarterNumber,
        CASE 
            WHEN o.customer_feedback = 'Very Bad' THEN 1
            WHEN o.customer_feedback = 'Bad' THEN 2
            WHEN o.customer_feedback = 'Okay' THEN 3
            WHEN o.customer_feedback = 'Good' THEN 4
            WHEN o.customer_feedback = 'Very Good' THEN 5
            ELSE NULL
        END AS feedback_num_value 
    FROM order_t o 
) AS Customer_Feedback_Scores;

-- Part 2: The Average Rating in each quarter
SELECT  
    QuarterNumber,
    ROUND(AVG(feedback_num_value), 2) as Quarterly_Avg_Rating
FROM (
    SELECT
        o.quarter_number AS QuarterNumber,
        CASE 
            WHEN o.customer_feedback = 'Very Bad' THEN 1
            WHEN o.customer_feedback = 'Bad' THEN 2
            WHEN o.customer_feedback = 'Okay' THEN 3
            WHEN o.customer_feedback = 'Good' THEN 4
            WHEN o.customer_feedback = 'Very Good' THEN 5
            ELSE NULL
        END AS feedback_num_value 
    FROM order_t o 
) AS Customer_Feedback_Scores
GROUP BY 
    QuarterNumber 
ORDER BY 
    QuarterNumber;

-- Question 5: Find the percentage distribution of feedback from the customers. Are customers getting more dissatisfied over time?

SELECT  
    QuarterNumber,
    ROUND(SUM(CASE WHEN feedback_num_value = 1 THEN 1 ELSE 0 END) * 100.0 /COUNT(feedback_num_value), 2) AS 'Very Bad(%)',	
    ROUND(SUM(CASE WHEN feedback_num_value = 2 THEN 1 ELSE 0 END) * 100.0 /COUNT(feedback_num_value), 2) AS 'Bad (%)',
    ROUND(SUM(CASE WHEN feedback_num_value = 3 THEN 1 ELSE 0 END) * 100.0 /COUNT(feedback_num_value), 2) AS 'Okay (%)',
    ROUND(SUM(CASE WHEN feedback_num_value = 4 THEN 1 ELSE 0 END) * 100.0 /COUNT(feedback_num_value), 2) AS 'Good (%)',
    ROUND(SUM(CASE WHEN feedback_num_value = 5 THEN 1 ELSE 0 END) * 100.0 /COUNT(feedback_num_value), 2) AS 'Very Good (%)'
FROM (
    SELECT
        o.quarter_number AS QuarterNumber,
        CASE 
            WHEN o.customer_feedback = 'Very Bad' THEN 1
            WHEN o.customer_feedback = 'Bad' THEN 2
            WHEN o.customer_feedback = 'Okay' THEN 3
            WHEN o.customer_feedback = 'Good' THEN 4
            WHEN o.customer_feedback = 'Very Good' THEN 5
            ELSE NULL
        END AS feedback_num_value 
    FROM order_t o 
) AS Customer_Feedback_Scores

GROUP BY 
    QuarterNumber 
ORDER BY 
    QuarterNumber; 

-- Question 6: What is the trend of the number of orders by quarter?

SELECT
    quarter_number AS QuarterNumber,
    COUNT(order_id) AS QuarterlyTotal
FROM 
    order_t 
GROUP BY 
    QuarterNumber
ORDER BY 
    QuarterNumber; 
    
-- Question 7: Calculate the net revenue generated by the company. What is the quarter-over-quarter % change in net revenue?

-- Part 1: Find the net revenue generated by the company
SELECT
    ROUND(SUM(quantity * vehicle_price * (1 - (discount / 100))), 2)
        AS Total_Net_Revenue
FROM order_t;

-- Part 2: QoQ % Change in Net Revenue

SELECT
    Sales_Quarter,
    ROUND(Net_Revenue, 2) AS Net_Revenue,
    ROUND(LAG(Net_Revenue) OVER(ORDER BY Sales_Quarter), 2) AS Previous_Quarter_Revenue,
    ROUND((Net_Revenue - LAG(Net_Revenue) OVER (ORDER BY Sales_Quarter)) * 100.0
    / LAG(Net_Revenue) OVER (ORDER BY Sales_Quarter),2) AS QoQ_Percentage_Change
FROM (
    SELECT 
        quarter_number AS Sales_Quarter,
        SUM(quantity*vehicle_price*(1-(discount / 100))) AS Net_Revenue
    FROM 
        order_t 
    GROUP BY 
        quarter_number
) AS QuarterlyRevenue

ORDER BY 
    Sales_Quarter;


-- Question 8: What is the trend of net revenue and orders by quarters?

SELECT
    quarter_number AS Sales_Quarter,
    ROUND(
        SUM(quantity*vehicle_price*(1-(discount / 100))),2) AS Net_Revenue,
    COUNT(order_id) AS Total_Orders
FROM 
    order_t 
GROUP BY 
    quarter_number

ORDER BY 
    Sales_Quarter;

-- Question 9: What is the average discount offered for different types of credit cards?

SELECT
    credit_card_type AS Card_Type,
    ROUND(AVG(o.discount), 2) AS Average_Card_Discount
FROM customer_t c 
    JOIN order_t o USING(customer_id)
GROUP BY
    Card_Type
ORDER BY
    Average_Card_Discount DESC;

-- Question 10: What is the average time taken to ship the placed orders for each quarter?
SELECT
    quarter_number AS Quarter,
    ROUND(AVG(JULIANDAY(ship_date)) - (JULIANDAY(order_date)),2) AS Average_Days_Since_Order
FROM 
    order_t
GROUP BY
    quarter_number
ORDER BY
    Quarter;
    
    
-- Appendix
-- Business Matrix Dervied Queries:

-- Total Revenue:
SELECT
    ROUND(SUM(quantity*vehicle_price),2) AS Total_Revenue
FROM 
    order_t;

-- Total Orders
SELECT
    COUNT(order_id) AS Total_Orders
FROM 
    order_t;

-- Total Customers
SELECT 
    COUNT(DISTINCT customer_id) AS Customers_Who_Placed_Orders
FROM order_t;

-- Average Rating
SELECT  
    ROUND(AVG(feedback_num_value), 2) as Overall_Avg_Rating
FROM (
    SELECT
        o.quarter_number AS QuarterNumber,
        CASE 
            WHEN o.customer_feedback = 'Very Bad' THEN 1
            WHEN o.customer_feedback = 'Bad' THEN 2
            WHEN o.customer_feedback = 'Okay' THEN 3
            WHEN o.customer_feedback = 'Good' THEN 4
            WHEN o.customer_feedback = 'Very Good' THEN 5
            ELSE NULL
        END AS feedback_num_value 
    FROM order_t o 
) AS Customer_Feedback_Scores;


-- Last Quarter Revenue:
Gross Revenue: (excluding discounts or deductions)
SELECT
    quarter_number AS Quarter_Number,
    ROUND(SUM(quantity*vehicle_price),2) AS Total_Revenue
FROM 
    order_t
GROUP BY 
    quarter_number
ORDER BY 
    Quarter_Number DESC
LIMIT 1; 

-- Last Quarter Orders:
SELECT
    quarter_number AS Quarter_Number,
    COUNT(order_id) AS Total_Orders
FROM 
    order_t
GROUP BY 
    quarter_number
ORDER BY 
    Quarter_Number DESC
LIMIT 1; 

-- Average Days to Ship:
SELECT
    ROUND(
        AVG(JULIANDAY(ship_date) - JULIANDAY(order_date)),
        0
    ) AS Average_Days_Since_Order
FROM 
    order_t;


-- % Good Feedback:
(including “Good” and “Very Good” customer ratings)
SELECT  
ROUND(
    (SUM(CASE WHEN feedback_num_value = 4 THEN 1 ELSE 0 END) +
     SUM(CASE WHEN feedback_num_value = 5 THEN 1 ELSE 0 END))
    * 100.0 / COUNT(feedback_num_value),
    2
) AS 'Good + Very Good (%)'
FROM (
    SELECT
        o.quarter_number AS QuarterNumber,
        CASE 
            WHEN o.customer_feedback = 'Very Bad' THEN 1
            WHEN o.customer_feedback = 'Bad' THEN 2
            WHEN o.customer_feedback = 'Okay' THEN 3
            WHEN o.customer_feedback = 'Good' THEN 4
            WHEN o.customer_feedback = 'Very Good' THEN 5
            ELSE NULL
        END AS feedback_num_value 
    FROM order_t o 
) AS Customer_Feedback_Scores;











